In [1]:
%run ./combinations_of_permutations.ipynb
from itertools import combinations, product
import numpy as np
from collections import Counter

The polynomials are not working super well. We have some options of how to proceed.

I suspect this will all work better if the partial polynomials are squares rather than rectangles. 


If the polynomials don't work, we can look at more clever ways to use them. Otherwise we have to use just the vectors. I need to work out how the polynomials affect the first rows.

In [37]:
R.<x,y> = PolynomialRing(QQ)
# polynomial of first m rows based on a k-permutation of [n]
def genPermPolynomial(p,n,m=None,k=None):
    if m==None:
        m=n
    l=len(p)
    if k==None:
        k=l
    return factorial(n-k)/binomial(n,k)*sum([binomial(x,j)*binomial(n-1-x,k-1-j)*binomial(y,p[j])*binomial(n-1-y,k-1-p[j]) for j in range(l)])

# first m rows of the above based on a k-permutation of [n]
def genPermMatrixByRow(p,n,m=None,k=None):
    if m==None:
        m=n
    l=len(p)
    if k==None:
        k=l
    if l==n:
        return matrix(QQ,m,n,lambda x,y:p[x]==y)
    return factorial(n-k)/binomial(n,k)*matrix(m,n,lambda x,y:sum([binomial(x,j)*binomial(n-1-x,k-1-j)*binomial(y,p[j])*binomial(n-1-y,k-1-p[j]) for j in range(l)]))

def genBinoms(p,n,m=None,k=None):
    
    if m==None:
        m=n
    l=len(p)
    if k==None:
        k=l
    return [binomial(x,j)*binomial(n-1-x,k-1-j)*binomial(y,p[j])*binomial(n-1-y,k-1-p[j]) for j in range(l)]

In [40]:
for perm in rho_star.get_terms():
    print("\n"+str(perm), end="\n\n")
    for m in range(1, n+1):
        slice_perm  = list(perm)[:m]
        print(slice_perm)
        print(genPermMatrixByRow(slice_perm,4,m,len(perm)))
        print()
        print(matrix(QQ,m,4,lambda x,y:genPermPolynomial(slice_perm,4,m,len(perm))(x,y)))
        print()


[0, 1, 2]

[0]
[9/4 3/4   0   0]

[9/4 3/4   0   0]

[0, 1]
[9/4 3/4   0   0]
[3/4 5/4   1   0]

[9/4 3/4   0   0]
[3/4 5/4   1   0]

[0, 1, 2]
[9/4 3/4   0   0]
[3/4 5/4   1   0]
[  0   1 5/4 3/4]

[9/4 3/4   0   0]
[3/4 5/4   1   0]
[  0   1 5/4 3/4]

[0, 1, 2]
[9/4 3/4   0   0]
[3/4 5/4   1   0]
[  0   1 5/4 3/4]
[  0   0 3/4 9/4]

[9/4 3/4   0   0]
[3/4 5/4   1   0]
[  0   1 5/4 3/4]
[  0   0 3/4 9/4]


[2, 1, 0]

[2]
[  0   0 3/4 9/4]

[  0   0 3/4 9/4]

[2, 1]
[  0   0 3/4 9/4]
[  0   1 5/4 3/4]

[  0   0 3/4 9/4]
[  0   1 5/4 3/4]

[2, 1, 0]
[  0   0 3/4 9/4]
[  0   1 5/4 3/4]
[3/4 5/4   1   0]

[  0   0 3/4 9/4]
[  0   1 5/4 3/4]
[3/4 5/4   1   0]

[2, 1, 0]
[  0   0 3/4 9/4]
[  0   1 5/4 3/4]
[3/4 5/4   1   0]
[9/4 3/4   0   0]

[  0   0 3/4 9/4]
[  0   1 5/4 3/4]
[3/4 5/4   1   0]
[9/4 3/4   0   0]


[1, 0, 3, 2]

[1]
[0 1 0 0]

[0 1 0 0]

[1, 0]
[0 1 0 0]
[1 0 0 0]

[0 1 0 0]
[1 0 0 0]

[1, 0, 3]
[0 1 0 0]
[1 0 0 0]
[0 0 0 1]

[0 1 0 0]
[1 0 0 0]
[0 0 0 1]

[1, 0, 3, 2]
[0 

In [58]:
#Now that we have verified that our polynomials are actually being correctly formed, we must see why we are failing to find a solution?
#It's possible the polys are actually rather more work than we need to be doing now that we look at it. They are going to have 2n terms which is only better if we are doing 
# more than two rows
matrix_list = []
poly_list = []
for perm in rho_star.get_terms():
    m= 2 
    slice_perm  = list(perm)[:m]
    matrix_list.append(genPermMatrixByRow(slice_perm,4,m,len(perm)))
    poly_list.append(genPermPolynomial(slice_perm,4,m,len(perm)))
    
R.<x,y> = PolynomialRing(QQ)
monomial_basis = monomials([x,y], [n,n])
b = vector(QQ, [1]+[0]*(len(monomial_basis)-1))

coeff_vectors_poly = [vector(QQ, [f.monomial_coefficient(m) for m in monomial_basis]) for f in poly_list]
coeff_vectors_matrix = [vector(QQ,mat.list()) for mat in matrix_list]

print(monomial_basis)
for i, poly in enumerate(poly_list):
    print(poly)
    print(coeff_vectors_poly[i])
    print()
    
Amat = matrix(coeff_vectors_matrix)
ones = vector(QQ,[1]*8)
try:
    solnones = Amat.solve_left(ones)
    print(solnones)
    
    poly_sum = sum([solnones[i]*poly_list[i] for i in range(len(poly_list))])
    
except ValueError:
    print("zinks")

    


[1, y, y^2, y^3, x, x*y, x*y^2, x*y^3, x^2, x^2*y, x^2*y^2, x^2*y^3, x^3, x^3*y, x^3*y^2, x^3*y^3]
5/16*x^2*y^2 - 17/16*x^2*y - 17/16*x*y^2 + 3/8*x^2 + 61/16*x*y + 3/8*y^2 - 15/8*x - 15/8*y + 9/4
(9/4, -15/8, 3/8, 0, -15/8, 61/16, -17/16, 0, 3/8, -17/16, 5/16, 0, 0, 0, 0, 0)

5/16*x^2*y^2 - 13/16*x^2*y - 17/16*x*y^2 + 41/16*x*y + 3/8*y^2 - 3/8*y
(0, -3/8, 3/8, 0, 0, 41/16, -17/16, 0, 0, -13/16, 5/16, 0, 0, 0, 0, 0)

-1/6*x^3*y^3 + 11/12*x^3*y^2 + 11/12*x^2*y^3 - 17/12*x^3*y - 5*x^2*y^2 - 17/12*x*y^3 + 1/2*x^3 + 91/12*x^2*y + 91/12*x*y^2 + 1/2*y^3 - 5/2*x^2 - 11*x*y - 5/2*y^2 + 3*x + 3*y
(0, 3, -5/2, 1/2, 3, -11, 91/12, -17/12, -5/2, 91/12, -5, 11/12, 1/2, -17/12, 11/12, -1/6)

1/6*x^3*y^3 - 7/12*x^3*y^2 - 11/12*x^2*y^3 + 5/12*x^3*y + 13/4*x^2*y^2 + 17/12*x*y^3 - 7/3*x^2*y - 31/6*x*y^2 - 1/2*y^3 + 15/4*x*y + 2*y^2 - 3/2*y
(0, -3/2, 2, -1/2, 0, 15/4, -31/6, 17/12, 0, -7/3, 13/4, -11/12, 0, 5/12, -7/12, 1/6)

1/6*x^3*y^2 + 1/12*x^2*y^3 - 1/3*x^3*y - 5/4*x^2*y^2 - 5/12*x*y^3 + 13/6*x^2*y +

In [59]:
print(rho_star)

1*(123) + 1*(321) + 1*(2143) + 1*(3412) + 1/2*(2413) + 1/2*(3142) 
